# Generated by Django 4.2.5 on 2023-10-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('del_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
